-- Generated by Lava 2000

use work.all;

entity
  fullAdder
is
port
  -- clock
  ( clk : in bit

  -- inputs
  ; inp_1 : in bit
  ; inp_2_1 : in bit
  ; inp_2_2 : in bit

  -- outputs
  ; outp_0 : out bit
  ; outp_1 : out bit
  );
end entity fullAdder;

architecture
  structural
of
  fullAdder
is
  signal w1 : bit;
  signal w2 : bit;
  signal w3 : bit;
  signal w4 : bit;
  signal w5 : bit;
  signal w6 : bit;
  signal w7 : bit;
  signal w8 : bit;
begin
  c_w3      : entity id    port map (clk, inp_2_1, w3);
  c_w4      : entity id    port map (clk, inp_2_2, w4);
  c_w2      : entity xor2  port map (clk, w3, w4, w2);
  c_w5      : entity id    port map (clk, inp_1, w5);
  c_w1      : entity xor2  port map (clk, w2, w5, w1);
  c_w7      : entity and2  port map (clk, w2, w5, w7);
  c_w8      : entity and2  port map (clk, w3, w4, w8);
  c_w6      : entity xor2  port map (clk, w7, w8, w6);

  -- naming outputs
  c_outp_0  : entity id    port map (clk, w1, outp_0);
  c_outp_1  : entity id    port map (clk, w6, outp_1);
end structural;
